/**
 * Type declarations for dicee-engine WASM module
 *
 * This module is generated by wasm-pack from the Rust engine.
 * The actual implementation lives in packages/engine.
 */

declare module 'dicee-engine' {
	/**
	 * Initialize the WASM module
	 */
	export default function init(): Promise<void>;

	/**
	 * Calculate scores for all 13 categories given current dice values.
	 *
	 * @param dice - Uint8Array of 5 dice values (1-6)
	 * @returns Uint8Array containing JSON-encoded ScoringResult[]
	 */
	export function calculate_category_scores(dice: Uint8Array): Uint8Array;

	/**
	 * Calculate probabilities and expected values for all available categories.
	 *
	 * @param dice - Uint8Array of 5 dice values (1-6)
	 * @param kept - Uint8Array of 5 kept flags (0 = not kept, 1 = kept)
	 * @returns Uint8Array containing JSON-encoded CategoryProbability[]
	 */
	export function calculate_probabilities(dice: Uint8Array, kept: Uint8Array): Uint8Array;
}
