-- ============================================================================
-- create_game_atomic: Atomically create game and player records
-- ============================================================================
-- Migration: 20260105000002_rpc_create_game
-- Purpose: Create game and all player records in a single transaction
-- Part of: Phase 4 - RPC-Based Persistence
--
-- Parameters:
--   p_game_id: UUID for the new game (generated by caller for idempotency)
--   p_room_code: 6-character room code
--   p_host_id: UUID of the host player
--   p_game_mode: 'solo', 'multiplayer', or 'tutorial'
--   p_settings: JSONB game settings
--   p_players: Array of game_player_input records
--
-- Returns: operation_result
--
-- Example:
--   SELECT * FROM create_game_atomic(
--     'uuid-here',
--     'ABC123',
--     'host-uuid',
--     'multiplayer',
--     '{}',
--     ARRAY[
--       ROW('player1-uuid', 0, 0, false)::game_player_input,
--       ROW('player2-uuid', 1, 1, false)::game_player_input
--     ]
--   );
-- ============================================================================

CREATE OR REPLACE FUNCTION create_game_atomic(
  p_game_id UUID,
  p_room_code TEXT,
  p_host_id UUID,
  p_game_mode TEXT,
  p_settings JSONB,
  p_players game_player_input[]
)
RETURNS operation_result
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_player game_player_input;
  v_player_count INTEGER := 0;
BEGIN
  -- Validate inputs
  IF p_game_id IS NULL THEN
    RETURN ROW(false, 'INVALID_INPUT', 'game_id is required', 0)::operation_result;
  END IF;

  IF p_game_mode NOT IN ('solo', 'multiplayer', 'tutorial') THEN
    RETURN ROW(false, 'INVALID_INPUT', 'game_mode must be solo, multiplayer, or tutorial', 0)::operation_result;
  END IF;

  IF array_length(p_players, 1) IS NULL OR array_length(p_players, 1) < 1 THEN
    RETURN ROW(false, 'INVALID_INPUT', 'at least one player is required', 0)::operation_result;
  END IF;

  -- Check for duplicate game_id (idempotency)
  IF EXISTS (SELECT 1 FROM games WHERE id = p_game_id) THEN
    -- Already created - return success for idempotency
    RETURN ROW(true, NULL, NULL, 0)::operation_result;
  END IF;

  -- Insert game record
  INSERT INTO games (
    id,
    room_code,
    host_id,
    status,
    game_mode,
    settings,
    created_at,
    started_at
  ) VALUES (
    p_game_id,
    p_room_code,
    p_host_id,
    'active',
    p_game_mode,
    COALESCE(p_settings, '{}'::jsonb),
    NOW(),
    NOW()
  );

  -- Insert all player records
  FOREACH v_player IN ARRAY p_players
  LOOP
    INSERT INTO game_players (
      game_id,
      user_id,
      seat_number,
      turn_order,
      is_connected,
      joined_at
    ) VALUES (
      p_game_id,
      v_player.user_id,
      v_player.seat_number,
      v_player.turn_order,
      true,
      NOW()
    );
    v_player_count := v_player_count + 1;
  END LOOP;

  -- Log for debugging
  RAISE LOG 'create_game_atomic: Created game % with % players', p_game_id, v_player_count;

  RETURN ROW(true, NULL, NULL, v_player_count + 1)::operation_result;

EXCEPTION
  WHEN unique_violation THEN
    RETURN ROW(false, 'DUPLICATE', 'Game or player record already exists', 0)::operation_result;
  WHEN foreign_key_violation THEN
    RETURN ROW(false, 'INVALID_REFERENCE', 'Referenced user does not exist', 0)::operation_result;
  WHEN OTHERS THEN
    RAISE LOG 'create_game_atomic error: % %', SQLSTATE, SQLERRM;
    RETURN ROW(false, SQLSTATE, SQLERRM, 0)::operation_result;
END;
$$;

-- Grant execute to service role only (called from DO)
REVOKE EXECUTE ON FUNCTION create_game_atomic FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION create_game_atomic FROM anon;
REVOKE EXECUTE ON FUNCTION create_game_atomic FROM authenticated;
GRANT EXECUTE ON FUNCTION create_game_atomic TO service_role;

COMMENT ON FUNCTION create_game_atomic IS
  'Atomically creates a game and all player records. Idempotent - safe to retry.';
